### ISSUE TITLE
To show the test points list which can be selected by users.

### ISSUE THREAD

**Issue by Desgard** [HackSwjtu/HackRunningGo-iOS#4]
The list data: [link](https://github.com/HackSwjtu/HackRunningGo/blob/master/okPoint.txt)

We need to name for every point to describe the position in SWJTU XiPu Zone. It is amazing for users. 😉😉😉

Just be in Chinese. 
## e.g

`103.985729, 30.771025` ~> `北区奇味干锅旁丁字路口`

**Comment by Desgard** [comment]
You can get the real address position by Baidu Mapping Tools: [Position Get](http://api.map.baidu.com/lbsapi/getpoint/index.html)

**Comment by lianglanzheng** [comment]
You can get the name of points from application data.
 (Android devices) Database file: /data/data/com.zjwh.android_wh_physicalfitness/database/sport
 ->Table:runPoint
     Col"desc" are names, "lat"&"lon" are coordinates.

**Comment by Desgard** [comment]
llz fix it! thx!
